application: dataset-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: api.application

builtins:
- remote_api: on

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?index.yaml
- ^(.*/)?.*\.py[co]
- google_appengine
- .coverage

